#!/bin/bash

##########################################################################
# Copyright (C) 2018  Irvine McMinn (irvine mcminn at gmail dot com)
#
# AvTools is a collection of tools to provide some common Window's features
# to Linux anti-virus products. . The project home page can be found at
# https://github.com/Irvinehimself/TheBeggarsHardeningProject
#
# AvTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AvTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AvTools.  If not, see <http://www.gnu.org/licenses/>.
############################################################################

#scan completed downloads

DownloadDir="$HOME/Downloads"
Sophos="$HOME/Pictures/LauncherIcons/Sophos.png"
SophosClear="$HOME/Pictures/LauncherIcons/SophosClear.png"
SophosAlert="$HOME/Pictures/LauncherIcons/SophosAlert.png"
DisplayTime="2000"


function LaunchAvScan(){
    notify-send -u NORMAL -t "$DisplayTime" "Patience! Scanning $1" --icon="$Sophos"
    AvTestResult=$(savscan -f -all -archive -loopback -pua -suspicious  "$1" | grep ">>> ")
	if ! [[ "$AvTestResult" == "" ]] ; then
            notify-send -u CRITICAL -t 0 "$AvTestResult" --icon="$SophosAlert"
        else
                notify-send -u NORMAL -t "$DisplayTime" "All clear $1" --icon="$SophosClear"
	fi
}

###### Main ######

inotifywait -qmr -e moved_to  --format '%w%f' $DownloadDir | \
while read Line ; do
    ### eliminate the intermediate file path, ".org.chromium.Chromium.", for Opera and other Chromium based browsers
    if [[ "$(echo $Line | grep '.org.chromium.Chromium.')" == "" ]] ; then
        LaunchAvScan "$Line" &
	fi
done
