#!/bin/bash

# Usage: add "ThunarAvScan %f" to Thunars RMB context menu
# Because 'savscan' raises privileges, seccomp will kill it inside Thunar's Firejail sandbox

Sophos="/home/stupidme/Pictures/LauncherIcons/Sophos.png"
SophosClear="$HOME/Pictures/LauncherIcons/SophosClear.png"
SophosAlert="$HOME/Pictures/LauncherIcons/SophosAlert.png"

# ### Main ###
notify-send -u NORMAL -t 10000 "Patience, running Sophos 'savscan' on $1" --icon="$Sophos"

AvTestResult=$(savscan -f -all -archive -loopback -pua -suspicious  $1 | grep ">>> ")

if [[ "$AvTestResult" == "" ]] ; then
        notify-send -u NORMAL -t 10000 "No viruses were discovered" --icon="$SophosClear"
    else
        notify-send -u NORMAL -t 10000 "$AvTestResult" --icon="$SophosAlert"
fi


