#!/bin/bash

##########################################################################
# Copyright (C) 2018  Irvine McMinn (irvine mcminn at gmail dot com)
#
# ApTools is a collection of monitoring and general security tools to make
# it easier to adopt good habits. The project home page can be found at
# https://github.com/Irvinehimself/TheBeggarsHardeningProject
#
# ApTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ApTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ApTools.  If not, see <http://www.gnu.org/licenses/>.
############################################################################

# A collection of useful Apparmor commands

source Hsa-Shared

PromptMsg="${Dimd}Commands: (S)tatus, (D)mesg, (A)udit or (Q)uit${End}"

SetTerminalTitle "AppArmorStatus"

ReadKey "$PromptMsg"
until echo $Key|grep -iq "q"; do
    printf '\n'
    case $Key in
        [sS]) echo -e "${Dimd}Apparmor status:${End}"
              sudo apparmor_status ;;
        [dD]) echo -e "${Dimd}dmesg grep Apparmor:${End}"
              sudo dmesg | grep -i "apparmor" ;;
        [aA]) echo -e "${Dimd}dmesg grep Audit:${End}"
              sudo dmesg | grep -i "audit" ;;
    esac
    printf '\n'
    ReadKey "$PromptMsg"
done
echo " Bye, have a nice day!"
