#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/TheBeggarsHardeningProject
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fj-Tools.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# This shell disables firejail symlinks by renaming my symlinking folder and, thus taking it out of the $PATH

# NOTE This assumes the following modification to the path in 'makepkg.conf' is always the last mod appended to the file
# PATH=":$PATH"
# PATH="${PATH/:\/usr\/local\/bin\/FjSymlinks:/:}"
# export PATH="${PATH#:}"
# ### see forum https://bbs.archlinux.org/viewtopic.php?pid=1743138

source Fj-Shared

function DisableSymlinks(){
	echo "Disabling Firejail symlinks"
	echo "Sorry, need root password"
	sudo mv "$FjSymlinks" "$FjSymlinksBack"
	# Disable symlinks for makepkg
	head -n -3  "$MakePkgConf" > "$TmpMkpkgConf"
	echo "#### FIREJAIL SYMLINKS DISABLED" >> "$TmpMkpkgConf"
	sudo mv "$TmpMkpkgConf" "$MakePkgConf"
}

# ### ### Main ### ###

SetTerminalTitle "Fj-DisableSymlinks"

if [ -d "$FjSymlinks" ]; then
    DisableSymlinks
fi

