#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/TheBeggarsHardeningProject
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fj-Tools.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# This shell re-enables firejail symlinks after they have been disabled by FjTools-DisableSymlinks

# NOTE This assumes the following modification to the path in 'makepkg.conf' is always the last mod appended to the file
# PATH=":$PATH"
# PATH="${PATH/:\/usr\/local\/bin\/FjSymlinks:/:}"
# export PATH="${PATH#:}"
# ### see forum https://bbs.archlinux.org/viewtopic.php?pid=1743138

source Fj-Shared

function EnableSymlinks(){
	echo "Enabling Firejail symlinks"
	echo "Sorry, need root password"
	sudo mv "$FjSymlinksBack" "$FjSymlinks"
	# Enable symlinks for makepkg
	head -n -1  "$MakePkgConf" > "$TmpMkpkgConf"
	echo 'PATH=":$PATH"' >> "$TmpMkpkgConf"
	echo 'PATH="${PATH/:\/usr\/local\/bin\/FjSymlinks:/:}"' >> "$TmpMkpkgConf"
	echo 'export PATH="${PATH#:}"' >> "$TmpMkpkgConf"
	sudo mv "$TmpMkpkgConf" "$MakePkgConf"
}


# ### ### Main ### ###

SetTerminalTitle "Fj-EnableSymlinks"

if [ -d "$FjSymlinksBack" ] ; then
    EnableSymlinks
fi
