#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/Irvines-Firejail-Extras
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fj-Tools.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# This shell re-enables firejail symlinks after they have been disabled by FjTools-DisableSymlinks

source Fj-Shared

function EnableSymlinks(){
	echo "Disabling Firejail symlinks"
	echo "Sorry, need root password"
	sudo mv "$FjSymlinksBack" "$FjSymlinks"
	# Enable symlinks for makepkg
	sudo sed -i 's/#PATH=/PATH=/g' "$MakePkgConf"
	sudo sed -i 's/#export /export "/g' "$MakePkgConf"
}


 ### End Functions

 ### ### Main ### ###

SetTerminalTitle "Fj-EnableSymlinks"

EnableSymlinks
