#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/Irvines-Firejail-Extras
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fj-Tools.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# Lists homegrown Firejail profiles

source Fj-Shared

function CheckOwner() {
    while read Line ; do
        ### Use package manager to check if profile is owned by firejail
        ProfileOwner=$(GetPckgOwner $EtcFirejail/$Line 2>/dev/null)
        ### StndError is redirected to /dev/null, so if owner is a nullstring,
        ### then it's a homegrown customisation
        if [[ "$ProfileOwner" = "" ]] ; then
            echo -e "$Line"
        fi
    done
}

 ### Start Main

# set title
SetTerminalTitle "Fj-HomeGrownProfiles"

echo -e ${Dimd}"The following firejail profiles are not owned by firejail:"${End}${Cyn}
ls "$EtcFirejail" | grep "profile" | CheckOwner | column -x
echo -e ${End}
echo ${Dimd}"And the following have local customisations:"${End}${Grn}
ls "$EtcFirejail" | grep "local" | CheckOwner | column -x
echo -e ${End}
echo -e ${Dimd}"(Hit return to close)"${End}
read Quit
