#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/TheBeggarsHardeningProject
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fj-Tools.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# Ideally, if I have got things correct, any problems with porting the collection of
# tools to other distro's can be solved solely by editing the paths in this common
# library, (FjTools-Shared,) of FjTools

source Fj-TerminalTricks

 ### ### Paths ### ###

# system
EtcFirejail="/etc/firejail"
UsrBinFirejail="/usr/bin/firejail"

UsrLocalBin="/usr/local/bin"
UsrBin="/usr/bin"

UsrLib="/usr/lib"
Etc="/etc"

NotifyIcon="/usr/share/pixmaps/firetools.png"

# FjSymlinks
FjSymlinks="$UsrLocalBin/FjSymlinks"
FjSymlinksBack="$FjSymlinks""Back"
MakePkgConf="/etc/makepkg.conf"
TmpMkpkgConf="/tmp/TmpMkpkgConf.tmp"


# FjWork
FjDebugWork="${HOME}/Documents/FjToolsWork/DebugProfiles"
FjDebugLog="$FjDebugWork/DebugLog"

 ### ### End paths

# Distro specific functions and variables that will need editing for non-arch distros

NoPckgOwns="error: No package owns"

function GetPckgOwner(){
    echo "$(pacman -Qoq $1)"
}



