#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/TheBeggarsHardeningProject
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fj-Tools.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# copy's all the profiles not  owned by Firejail to my git folder

source Fj-Shared

# Private Paths
GitHome="${HOME}/Git/TheBeggarsHardeningProject"
GitFirejail="$GitHome/Firejail"
GitFirejailProfiles="$GitFirejail/Profiles"
GitFirejailLocals="$GitFirejail/LocalCustomisations"
GitFjTools="$GitHome/FjTools"
GitHsTools="$GitHome/HsTools"
GitApparmor="$GitHome/AppArmor"
GitApparmorProfileList="$GitApparmor/AppArmor-ProfileList"
GitAppArmorProfiles="$GitApparmor/apparmor.d"
GitAppArmorLocals="$GitAppArmorProfiles/local"
GitAvTools="$GitHome/AvTools"
UserSystemd="${HOME}/.config/systemd/user"

# End Private Paths

# Prompts, Messages and Strings
ChLocalCustomisations="The following '.local' customisations further restrict the upstream profile:"
ChNotYetSubmitted="The following profiles have not yet been submitted for inclusion upstream:"
GrepTestLocals="# Further restrict the"
GrepTestProfiles="will be automatically replaced when"

# End Prompts, Messages and Strings

function CheckOwner() {
    while read Line ; do
        ### Use package manager to check if profile is owned by firejail
        ProfileOwner=$(GetPckgOwner $EtcFirejail/$Line 2>/dev/null)
        ### StndError is redirected to /dev/null, so if owner is a nullstring,
        ### then it's a homegrown customisation
        if [[ "$ProfileOwner" = "" ]] ; then
            #echo "$Line"
            echo "$Line"
        fi
    done
}

function CopyLsGrep(){
    ls $1 | grep $2 | CheckOwner |\
    while read Line ; do
        cp "$1/$Line" $3
    done
}


function UpdateFirejailContentLists(){
	echo "Updating $1"
	echo "$2" > "$GitFirejail/$1"
	echo >> "$GitFirejail/$1"
	cd "$3"
    grep -l "$4" *"$5" >> "$GitFirejail/$1"
}

function UpdateApparmor(){
    echo "Updating AppArmor profiles"
    cat "$GitApparmorProfileList" | grep -v "#" |\
    while read Line ; do
        if ! [[ "$Line" == "" ]] ; then
        	cp "/etc/apparmor.d/$Line" "$GitAppArmorProfiles/$Line"
        	cp "/etc/apparmor.d/local/$Line" "$GitAppArmorLocals/$Line"
        fi
    done
}

function UpdateSophos() {
    echo "Updating Sophos stuff"
    cp "$UserSystemd/SophosAv--WatchDownloads.service" "$GitAvTools/UserSystemd/SophosAv--WatchDownloads.service"
    cp "$UsrLocalBin/SophosAv--WatchDownloads"  "$GitAvTools/SophosAv--WatchDownloads"
    cp "$UsrLocalBin/ThunarAvScan" "$GitAvTools/ThunarAvScan"
}

 ### ### Start Main ### ###

SetTerminalTitle "Fj-UpdateGit"

echo "Updating profiles"
# copy all the homegrown profiles to git folder
CopyLsGrep "$EtcFirejail" "profile" "$GitFirejailProfiles"

echo "Updating local customisations"
# copy local customisations to git folder
CopyLsGrep "$EtcFirejail" "local" "$GitFirejailLocals"

echo "Updating FjTools"
# copy Fj-Tools to git folder
CopyLsGrep "$UsrLocalBin" "Fj-" "$GitFjTools"

# Update content lists
UpdateFirejailContentLists "Firejail-RestrictiveLocalCustomisations" "$ChLocalCustomisations" "$GitFirejailLocals" "$GrepTestLocals" ".local"

UpdateFirejailContentLists "Firejail-ProfilesNotYetSubmittedUpstream" "$ChNotYetSubmitted" "$GitFirejailProfiles" "$GrepTestProfiles" ".profile"

# Update Apparmor stuff
UpdateApparmor

# Update Sophos stuff
UpdateSophos

echo "Updating HsTools"
# copy Hs-Tools to git folder
CopyLsGrep "$UsrLocalBin" "Hs-" "$GitHsTools"
CopyLsGrep "$UserSystemd" "Hs-" "$GitHsTools/UserSystemd"

ReadQuit ""
echo "Bye :)"
