#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/Irvines-Firejail-Extras
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ArchAudit-Report.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# A wrapper to launch applications with 'firejail --debug'

source FjTools-Shared

 ### ### Functions ### ###

function GetAppName(){
    echo "FjTools Firejail debug wrapper $1"
	if [[ $1 = "" ]] ; then
			echo "Enter application name, null string to cancel"
			read AppName
			Profile="profile=$EtcFirejail/$AppName.profile"
	    else
	            ProfilePath="$EtcFirejail/$1"
	            AppName="$1"
	fi
}

function BackUpProfile(){
    cp -f $FjDebugWork/$AppName.profile $FjDebugWork/$AppName.profile.back 2>/dev/null
    cp -f $FjDebugWork/$AppName.local $FjDebugWork/$AppName.local.back 2>/dev/null
    cp -f $FjDebugWork/$AppName.net $FjDebugWork/$AppName.net.back 2>/dev/null
    cp -f $EtcFirejail/$AppName.profile $FjDebugWork/$AppName.profile 2>/dev/null
    cp -f $EtcFirejail/$AppName.local $FjDebugWork/$AppName.local 2>/dev/null
    cp -f $EtcFirejail/$AppName.net $FjDebugWork/$AppName.net 2>/dev/null
}


 ### End Functions


 ### ### Main ### ###
GetAppName
if ! [[ $AppName = "" ]] ; then
    mkdir -p "$FjDebugWork"
    Launch="y"
    until ! [[ "$Launch" = "y"  ]] ; do
        BackUpProfile
        # tee both stderr and stdout to log file
        firejail --debug --$Profile $AppName 2>&1 | tee "$DebugFile"
        echo
        echo "Launch $AppName again? y/n (default no)"
        read -n1 -s Launch
        echo
    done
fi
echo "Bye :)"
