#!/bin/bash

# Lists symlinked Firejail profiles

# Ideally, if I have got things correct, any problems with porting the collection of tools
# to other distro's can be solved solely by eiting the paths in FjTools-Shared
source FjTools-Shared


 ### Start Main
echo -e ${Dimd}"The following firejail profiles have been symlinked:"${End}${Cyn}
ls -la "$FjSymlinks" | grep "$UsrBinFirejail" | cut -d':' -f2 | cut -d' ' -f2 | column -x
echo -e ${End}${Dimd}"(Hit return to close)"${End}
read Quit
