#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/Irvines-Firejail-Extras
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ArchAudit-Report.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# Shell to backup or restore /etc/firejail/<AppName>.*

source FjTools-Shared

 ### ### Functions ### ###
function BackUpProfile(){
    cp $EtcFirejail/$AppName.profile $LastCopy/$AppName.profile 2>/dev/null
    cp $EtcFirejail/$AppName.local $LastCopy/$AppName.local 2>/dev/null
    cp $EtcFirejail/$AppName.net $LastCopy/$AppName.net 2>/dev/null
}

function RestoreProfile(){
    echo "Sorry, need sudo permission to copy files to /etc/firejail"
    sudo cp $LastCopy/$AppName.profile $EtcFirejail/$AppName.profile 2>/dev/null
    sudo cp $LastCopy/$AppName.local $EtcFirejail/$AppName.local 2>/dev/null
    sudo cp $LastCopy/$AppName.net $EtcFirejail/$AppName.net 2>/dev/null
}

function GetAppName(){
    echo "FjTools:  Create last working copy backups of <AppName>.profile, <AppName>.local and <AppName>.net"
	echo "Enter application name, null string to cancel"
	read AppName
}


 ### End Functions


 ### ### Main ### ###
GetAppName
if ! [[ $AppName = "" ]] ; then
    LastCopy="$FjDebugFolder/$AppName/LastWorkingCopy"
    mkdir -p "$LastCopy"
    echo "(B)ackup or (R)estore $AppName profile and customisations? (default is 'B'/'b'"
    read -n1 -s Key
    if  echo "$Key" |grep -iq "r" ; then
            RestoreProfile
        else
                BackUpProfile
    fi
fi
echo "Bye :)"
