#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/Irvines-Firejail-Extras
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ArchAudit-Report.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# Shell to find unused Firejail profiles

source FjTools-Shared

 ### Prompts
PrmptMsg1="Create firejail symlinks in $FjSymlinks ? y/n"
PrmptMsg2="Enter profile name, null string to terminate"
 ### End prompts



 ### ### ### Start Main ### ### ###
printf '%-50s%-50s\n' ${Dimd}${Ulnd}"PROFILE NAME"${End} ${Dimd}${Ulnd}"OWNER'S NAME"${End}
ls "$EtcFirejail" | grep "profile" |\
    while read Line ; do
        ProfileName=${Line%%.profile}
        # Use package manager to check if bin file exists
        Owner=$(GetPckgOwner $UsrBin/$ProfileName 2>&1)
        # StndError is redirected to Stndout, So...
        if [[ ! "$Owner" = *"No such file or directory" ]] ; then
            if [[ "$Owner" = "$NoPckgOwns"* ]] ; then
                # This deals with un-registered custom tweaks and installs to /usr/bin
                # In particular, my custom link to /usr/lib/ThunarBulkRename
                Owner="StupidMe"
            fi
            ### Silently check if profile is symlinked to firejail
            if ! ls "$FjSymlinks" | grep -x "$ProfileName" 1>/dev/null ; then
                printf '%-50s%-50s\n' ${Grn}"$ProfileName"${End} ${Blu}"$Owner"${End}
            fi
        fi
    done
 ### Option to create symlinks
echo "$PrmptMsg1"
read -n1 -s Key
if  echo "$Key" | grep -iq "y" ; then
    Target="Dummy"
    until [[ "$Target" = "" ]] ; do
        echo "$PrmptMsg2"
        read Target
        if [[ ! "$Target" = "" ]] ; then
            sudo ln -s $UsrBinFirejail "$FjSymlinks/$Target"
        fi
    done
fi
