#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/Irvines-Firejail-Extras
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ArchAudit-Report.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# shared functions that are not specific to a particular distro

source FjTools-Shared

function EchoToScreen(){
    echo "$1"
    echo
}

function CheckOwner() {
    while read Line ; do
        ### Use package manager to check if profile is owned by firejail
        ProfileOwner=$(GetPckgOwner $EtcFirejail/$Line 2>/dev/null)
        ### StndError is redirected to /dev/null, so if owner is a nullstring,
        ### then it's a homegrown customisation
        if [[ "$ProfileOwner" = "" ]] ; then
            #echo "$Line"
            echo "$Line"
        fi
    done
}

function CopyLsGrep(){
    ls $1 | grep $2 | CheckOwner |\
    while read Line ; do
        cp "$1/$Line" $3
    done
}

function AddBisectionChopToFile(){
	echo "### Bisection Chop ###" >> "$2"
	echo "$1" >> "$2"
	echo >> $2
}
