#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/Irvines-Firejail-Extras
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ArchAudit-Report.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# Shell to backup or restore /etc/firejail/<AppName>.*

source FjTools-Shared
source FjTools-Includes

 ### ### Functions ### ###
function BackUpProfile(){
    cp $EtcFirejail/$AppName.profile $FjBackupProfiles/$AppName.profile 2>/dev/null
    cp $EtcFirejail/$AppName.local $FjBackupProfiles/$AppName.local 2>/dev/null
    cp $EtcFirejail/$AppName.net $FjBackupProfiles/$AppName.net 2>/dev/null
}

function RestoreProfile(){
    # Probably the stupidest thing in Linux, redirecting "stderr" also redirects "sudo" !!!!
    if [[ -e $1 ]] ; then
        sudo cp $2 $1
    fi
}

function GetAppName(){
	echo "Enter application name, null string to cancel"
	read AppName
}

 ### End Functions


 ### ### Main ### ###
echo "FjTools:  Create backups of <AppName>.profile, <AppName>.local and <AppName>.net "
mkdir -p "$FjBackupProfiles"
echo "(B)ackup or (R)estore (default is 'B'/'b')"
read -n1 -s Key
if  echo "$Key" |grep -iq "r" ; then
        # Restoring profiles
        GetAppName
        echo "Sorry, need sudo permission to copy files to /etc/firejail"
        RestoreProfile $FjBackupProfiles/$AppName.profile $EtcFirejail/$AppName.profile
        RestoreProfile $FjBackupProfiles/$AppName.local $EtcFirejail/$AppName.local
        RestoreProfile $FjBackupProfiles/$AppName.net $EtcFirejail/$AppName.net
    else
            echo
            echo "Backup (A)ll local customisations or (N)amed <application (default is 'N'/'n'"
            read -n1 -s Key
			if  echo "$Key" |grep -iq "A" ; then
			        # Backing up ALL local customisations
			        CopyLsGrep "$EtcFirejail" "profile" "$FjBackupProfiles"
			        CopyLsGrep "$EtcFirejail" "local" "$FjBackupProfiles"
			        CopyLsGrep "$EtcFirejail" "net" "$FjBackupProfiles"
			    else
			             # Backing up named profile and local customisations
			             GetAppName
			             BackUpProfile
			fi
fi
echo "Bye :)"
