#!/bin/bash

###############################################
# Copyright (C) 2017  Irvine McMinn (irvine mcminn at gmail dot com)
#
# FjTools is a collection of extra profiles, local customisations and
# tools for Firejail. The project home page can be found at
# https://github.com/Irvinehimself/Irvines-Firejail-Extras
#
# FjTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FjTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ArchAudit-Report.  If not, see <http://www.gnu.org/licenses/>.
###############################################

# Guess an applications private-etc
source FjTools-Shared
source FjTools-Includes

 ### ### Functions ### ###
function GetAppName(){
    # If AppName has not been assigned manually, then ask user
    if [[ "$AppName" = "" ]] ; then
    	echo "Guess contents of private-etc"
    	echo "Enter application name, null string to cancel"
    	read AppName
    	echo
	fi
}

function GetDependencies(){
	if ! [ -e  "$FjDependencyChain-$AppName" ] ; then
	        FjTools-GetAppDependencies "$AppName"
	    else
	            EchoToScreen "Dependency chain already exist, skipping get dependencies"
	fi
	DependencyChain="$(cat $FjDependencyChain-$AppName)"
}

function GetPrivateEtcSugestions(){
    local Line="Dummy"
    local PkgOwner="Dummy"
    local DepTest="Dummy"
    local Count="0"
    local PrivateEtcString=""
    ls "$Etc" |\
    (
    while read Line ; do
        PkgOwner=$(GetPckgOwner "$Etc/$Line" 2>&1)
        #EchoToScreen "$Line is owned by $PkgOwner"
        if [[ "$DependencyChain" = *",$PkgOwner,"* ]] ; then
            	EchoToScreen "Adding $Line to bisection string"
            	PrivateEtcString="$PrivateEtcString,$Line"
            	((Count++))
            	if [[ "$Count" = "$BisectionChop"  ]] ; then
            	    Count="0"
            	    EchoToScreen "Adding bisection chop to GuessPrivateEtc-$AppName"
            	    AddBisectionChopToFile "$PrivateEtcString" "$FjGuessPrivateEtc-$AppName"
            	    PrivateEtcString=""
            	fi
            elif  [[ "$PkgOwner" = *"$NoPckgOwns"* ]] ; then
                EchoToScreen "No package owns $Line to Adding NoPkgOwns file"
                echo "$Line" >> $FjPrivateEtcNoPkgOwns
        fi
    done
    EchoToScreen "Adding final chop to GuessPrivateEtc-$AppName"
    AddBisectionChopToFile "$PrivateEtcString" "$FjGuessPrivateEtc-$AppName"
    )
}

 ### End functions

 ### ### Main ### ###

GetAppName
if ! [[ "$AppName" = "" ]] ; then
    GetDependencies
    mkdir -p "$FjPrivateEtcWork"
    echo "" > "$FjGuessPrivateEtc-$AppName"         # Reset
    echo "" > "$FjPrivateEtcNoPkgOwns"              # Reset
    GetPrivateEtcSugestions
    cp $FjDependencyNotFound-$AppName $FjPrivateEtcNotFound-$AppName
    EchoToScreen "You can find the private-etc suggestions at $FjGuessPrivateEtc-$AppName"
    #EchoToScreen "Hit return to quit"
    #read Quit
fi
