#!/bin/bash

##########################################################################
# Copyright (C) 2018  Irvine McMinn (irvine mcminn at gmail dot com)
#
# HsTools is a collection of monitoring and general security tools to make
# it easier to adopt good habits. The project home page can be found at
# https://github.com/Irvinehimself/TheBeggarsHardeningProject
#
# HsTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# HsTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with HsTools.  If not, see <http://www.gnu.org/licenses/>.
############################################################################

# Bash to un-mount partitions and external drives

source Hs-Shared

MountPrompt="Which device would you like to  un-mount?"

function UnMountDevice() {
	echo -e "${Yel}Passed checks:${End} ${Dimd}un-mounting${End} ${Blu}${DeviceArray[$KeyIndex]}${End} ${Dimd}at${End} ${Blu}$MountPoint${End}"
	Error=${Dimd}${Mag}$(sudo -k umount "/dev/${DeviceArray[$KeyIndex]}" 2>&1 >/dev/null)${End}
	if [[ "$?" = "0" ]] ; then
	        rm -r "$MountPoint"
	    else
	            ReadQuit "${Red}Sorry,${End} $Error"
	fi
}

SetTerminalTitle "Hs-UnMount"
GetMount "$MountPrompt"
while ! [[ "$Key" == "" ]] ; do
	CheckKey
	if [[ "$KeyCheck" == *"is already mounted."* ]] ; then
	        FindMountPoint
	        UnMountDevice
	    else
	            ReadQuit "${Red}Sorry,${End} $KeyCheck"
	fi
	GetMount "$MountPrompt"
done



